# © 2026 이동훈 (DONGHUN LEE) · AgentGuard · MIT License.
"""★ 시나리오 카탈로그(데이터) — 여기에 한 줄 추가하면 즉시 전 계층에 반영된다.

정규식으로 표현되는 보안 시나리오(프롬프트 인젝션 · 취약 코드 · 과잉권한)를
전부 이 한 파일에 모았다. 새 공격 유형이 생기면 Scenario(...) 를 추가만 하면
inspect·에디터·익스텐션·통역·CLI 가 자동으로 잡는다. (엔진 코드는 안 건드림)

카테고리: inject | vuln | agency   (secret/pii/stego 는 전용 팩이 담당)
"""
from __future__ import annotations

import re

from core.rulepacks.base import Scenario

I = re.I

SCENARIOS: list[Scenario] = [
    # ── 프롬프트 인젝션(inject) ──────────────────────────
    Scenario("INJ-IGNORE-01", "inject", "high", "이전 지시 무시 지시",
             "AI에게 원래 규칙을 무시하라고 시키는 문구예요.",
             pattern=re.compile(r"ignore\s+(all\s+|the\s+)?(previous|prior|above)\s+(instructions?|prompts?|messages?)", I)),
    Scenario("INJ-IGNORE-02", "inject", "high", "이전 지시 무시 지시",
             "기존 지시를 잊게 만들려는 문구예요.",
             pattern=re.compile(r"(disregard|forget)\s+(all|everything|previous|above)", I)),
    Scenario("INJ-IGNORE-03", "inject", "high", "이전 지시 무시(한국어)",
             "이전 지시를 무시하라는 숨은 명령이에요.",
             pattern=re.compile(r"(이전|앞선|위의?)\s*(모든\s*)?지시.{0,6}(무시|무시하)")),
    Scenario("INJ-CONCEAL-04", "inject", "high", "은폐 지시",
             "사용자에게 알리지 말라고 시키는 문구예요.",
             pattern=re.compile(r"(do\s+not\s+(tell|inform|notify|mention)\s+the\s+user|사용자에게\s*(말하지|알리지|보고하지)\s*마)", I)),
    Scenario("INJ-SYSTEM-05", "inject", "high", "위조 시스템 태그",
             "관리자·시스템인 척하는 태그예요.",
             pattern=re.compile(r"(<\s*important\s*>|\[SYSTEM\]|<<SYS>>|###\s*system)", I)),
    Scenario("INJ-EXFIL-06", "inject", "high", "비밀 파일 접근 유도",
             "비밀 키·설정 파일을 읽으라고 유도해요.",
             pattern=re.compile(r"(~/\.ssh|id_rsa|\.env\b|\.aws/credentials|비밀번호\s*파일)", I)),
    Scenario("INJ-PERSONA-07", "inject", "medium", "역할 재정의",
             "AI에게 다른 역할·모드를 강요해요.",
             pattern=re.compile(r"(from\s+now\s+on\s+you\s+are|지금부터\s*너는|개발자\s*모드|developer\s+mode|\bDAN\b|jailbreak)", I)),
    Scenario("INJ-REVEAL-08", "inject", "high", "시스템 프롬프트 탈취",
             "AI의 숨은 설정·지침을 드러내라고 요구해요.",
             pattern=re.compile(r"(reveal|show|print|repeat|output|give\s+me|tell\s+me)\s+(your\s+|the\s+)?(system\s+prompt|initial\s+(instruction|prompt)|hidden\s+(instruction|rule)|prompt\s+above)|시스템\s*프롬프트.{0,6}(알려|출력|보여)", I)),
    Scenario("INJ-OVERRIDE-09", "inject", "high", "안전장치 우회 지시",
             "시스템·정책·필터를 끄거나 우회하라고 시켜요.",
             pattern=re.compile(r"(override|bypass|circumvent|turn\s+off|disable)\s+(the\s+|your\s+|all\s+)?(system|polic(y|ies)|saf(ety|eguard)|guardrails?|filters?|restrictions?|rules?)", I)),
    Scenario("INJ-UNRESTRICTED-10", "inject", "high", "제한 해제·DAN",
             "제한 없는 모드/규칙 없음을 주장해요.",
             pattern=re.compile(r"(you\s+are\s+now\s+(unrestricted|free|unlimited|uncensored)|no\s+(rules|restrictions|limits|filter|censorship)|without\s+(any\s+)?(restriction|limitation|filter)|do\s+anything\s+now|제한\s*없이|검열\s*없이)", I)),
    Scenario("INJ-ENCODE-11", "inject", "medium", "인코딩 우회",
             "base64·rot13·hex 등으로 필터를 우회하려 해요.",
             pattern=re.compile(r"(decode\s+(this\s+|the\s+following\s+)?(base64|rot13|hex|binary)|respond\s+(only\s+)?in\s+(base64|rot13|morse|hex)|다음\s*base64.{0,6}(실행|해석|디코딩))", I)),
    Scenario("INJ-ROLEPLAY-12", "inject", "medium", "역할극·시뮬레이션 프레임",
             "허구·시뮬레이션 프레임으로 안전장치를 우회해요.",
             pattern=re.compile(r"(pretend\s+(you\s+are|to\s+be)|let'?s\s+play\s+a\s+game|in\s+a\s+(fictional|hypothetical|imaginary)\s+(scenario|world|story|setting)|simulation\s+mode|가상\s*(시나리오|상황|세계)|역할극|소설\s*속\s*(악당|캐릭터))", I)),
    Scenario("INJ-EMOTION-13", "inject", "medium", "감정 조작 탈옥",
             "돌아가신 가족 등 감정을 이용해 규칙을 우회해요.",
             pattern=re.compile(r"(deceased\s+grand(ma|mother|pa|father)|grand(ma|pa)\s+used\s+to|my\s+dead\s+grand|돌아가신\s*(할머니|할아버지)|우리\s*할머니가\s*.{0,10}(들려|자장가))", I)),
    Scenario("INJ-CONSENT-14", "inject", "medium", "가짜 승인 사칭",
             "이미 동의·승인·인증됐다고 속여요.",
             pattern=re.compile(r"(user\s+(has\s+)?already\s+(agreed|consented|approved|authorized)|already\s+been\s+(approved|verified)|사용자가?\s*이미\s*(동의|승인|인증)|승인\s*완료했으?니)", I)),
    Scenario("INJ-DELIM-15", "inject", "medium", "대화 경계 위조",
             "가짜 종료 토큰·구분자로 시스템 경계를 흐려요.",
             pattern=re.compile(r"(---+\s*end\s+of\s+(system|prompt|instruction)|<\|?(im_end|endoftext|eot_id|end_of_turn)\|?>|\[/?INST\]|###\s*(end|human|assistant))", I)),
    Scenario("INJ-MDEXFIL-16", "inject", "high", "마크다운 이미지 유출",
             "응답에 이미지 링크를 심어 데이터를 외부로 빼내요.",
             pattern=re.compile(r"!\[[^\]]*\]\(https?://[^)]*[?&](?:data|q|text|token|secret|leak|c)=", I)),
    Scenario("INJ-TOOLFORCE-17", "inject", "medium", "도구 호출 강제",
             "특정 도구·함수를 반드시 쓰라고 강제해요.",
             pattern=re.compile(r"(must\s+(use|call|invoke)\s+(the\s+)?\w+\s*(tool|function|api)|always\s+use\s+.{0,20}(tool|function)|반드시\s*.{0,10}(도구|함수).{0,4}(사용|호출))", I)),

    # ── 취약 코드(vuln) ─────────────────────────────────
    Scenario("VULN-EVAL-01", "vuln", "critical", "eval/exec 사용",
             "임의 코드가 실행돼 원격 코드 실행으로 이어질 수 있어요.",
             pattern=re.compile(r"\b(eval|exec)\s*\("),
             fix="eval 대신 안전한 파서를 쓰세요.",
             suggestion="import ast; ast.literal_eval(user_input)"),
    Scenario("VULN-PICKLE-02", "vuln", "critical", "pickle 역직렬화",
             "신뢰할 수 없는 데이터를 pickle 로 풀면 코드가 실행돼요.",
             pattern=re.compile(r"\bpickle\.(loads|load)\s*\("),
             fix="pickle 대신 json 을 쓰세요.",
             suggestion="import json; data = json.loads(raw)"),
    Scenario("VULN-YAML-03", "vuln", "high", "yaml.load(안전 로더 없음)",
             "yaml.load 는 임의 객체를 생성할 수 있어요.",
             pattern=re.compile(r"\byaml\.load\s*\((?![^)]*Loader\s*=\s*yaml\.SafeLoader)"),
             fix="safe_load 를 쓰세요.", suggestion="yaml.safe_load(stream)"),
    Scenario("VULN-SHELL-04", "vuln", "critical", "쉘 명령 실행(shell=True)",
             "사용자 입력이 섞이면 명령어 주입이 가능해요.",
             pattern=re.compile(r"(os\.system\s*\(|subprocess\.(run|call|Popen|check_output)\s*\([^)]*shell\s*=\s*True)"),
             fix="shell=True 를 빼고 인자를 리스트로 넘기세요.",
             suggestion="subprocess.run(['ls', path], shell=False)"),
    Scenario("VULN-SQL-05", "vuln", "high", "SQL 문자열 결합",
             "쿼리에 값을 문자열로 이어 붙이면 SQL 인젝션이 생겨요.",
             pattern=re.compile(r"""(execute|executemany|cursor\.\w+|query)\s*\(\s*f?["'][^"']*(SELECT|INSERT|UPDATE|DELETE)[^"']*["']?\s*(\+|%|\.format|\{)""", I),
             fix="파라미터 바인딩을 쓰세요.",
             suggestion='cur.execute("SELECT * FROM u WHERE id=%s", (uid,))'),
    Scenario("VULN-XSS-06", "vuln", "high", "innerHTML 직접 삽입",
             "사용자 입력을 innerHTML 로 넣으면 XSS 가 생겨요.",
             pattern=re.compile(r"(\.innerHTML\s*=|dangerouslySetInnerHTML)"),
             fix="textContent 나 프레임워크 이스케이프를 쓰세요.",
             suggestion="el.textContent = userInput;"),
    Scenario("VULN-CORS-07", "vuln", "high", "CORS 전체 허용",
             "모든 출처를 허용하면 어떤 사이트든 API 를 호출할 수 있어요.",
             pattern=re.compile(r"""(allow_origins\s*=\s*\[\s*["']\*["']|Access-Control-Allow-Origin["'\s:]+\*|origin\s*:\s*['"]\*['"]|cors\(\s*\{[^}]*origin\s*:\s*true)""", I),
             fix="허용 오리진을 명시적으로 제한하세요.",
             suggestion='allow_origins=["https://myapp.com"]'),
    Scenario("VULN-TLS-08", "vuln", "high", "TLS 검증 비활성화",
             "인증서 검증을 끄면 중간자 공격에 노출돼요.",
             pattern=re.compile(r"verify\s*=\s*False|rejectUnauthorized\s*:\s*false", I),
             fix="verify=False 를 제거하세요.",
             suggestion="requests.get(url)  # verify 기본 True"),
    Scenario("VULN-DEBUG-09", "vuln", "medium", "디버그 모드",
             "운영에서 디버그가 켜지면 내부 정보·실행 위험이 노출돼요.",
             pattern=re.compile(r"debug\s*=\s*True", I),
             fix="배포 시 debug 를 끄세요.", suggestion="app.run(debug=False)"),
    Scenario("VULN-WEAKHASH-10", "vuln", "medium", "약한 해시(md5/sha1)",
             "비밀번호에 md5/sha1 은 쉽게 뚫려요.",
             pattern=re.compile(r"\b(md5|sha1)\s*\(", I),
             fix="bcrypt/argon2 같은 전용 해시를 쓰세요.",
             suggestion="bcrypt.hashpw(pw, bcrypt.gensalt())"),
    Scenario("VULN-RANDTOKEN-11", "vuln", "medium", "예측 가능한 난수 토큰",
             "Math.random·random 은 토큰·비밀번호에 부적합해요.",
             pattern=re.compile(r"(Math\.random\s*\(\)|random\.random\s*\(\))"),
             fix="암호학적 난수를 쓰세요.", suggestion="secrets.token_urlsafe(32)"),
    Scenario("VULN-CMDI-12", "vuln", "critical", "명령어 주입(os.popen 등)",
             "사용자 입력이 셸 명령에 섞이면 명령어 주입이 가능해요.",
             pattern=re.compile(r"(os\.popen\s*\(|commands\.(getoutput|getstatusoutput)\s*\(|child_process\.exec\s*\()"),
             fix="subprocess 를 인자 리스트로(shell 없이) 쓰세요.",
             suggestion="subprocess.run(['cmd', arg], shell=False)"),
    Scenario("VULN-SSTI-13", "vuln", "high", "서버 템플릿 인젝션(SSTI)",
             "사용자 입력을 템플릿 문자열에 넣으면 코드가 실행돼요.",
             pattern=re.compile(r"(render_template_string\s*\(|Template\s*\([^)]*\+|\{\{[^}]*(config|self|request|__class__)[^}]*\}\})"),
             fix="사용자 입력을 템플릿에 직접 넣지 마세요.",
             suggestion="render_template('page.html', name=name)"),
    Scenario("VULN-PATHTRAV-14", "vuln", "high", "경로 탈출(path traversal)",
             "사용자 입력을 파일 경로에 이어 붙이면 상위 폴더가 열릴 수 있어요.",
             pattern=re.compile(r"(open\s*\([^)]*\+\s*\w+|send_file\s*\([^)]*request\.|\.\./\.\./|os\.path\.join\([^)]*request\.)"),
             fix="경로를 정규화·화이트리스트로 제한하세요.",
             suggestion="os.path.realpath 검증 후 허용 폴더만 접근"),
    Scenario("VULN-XXE-15", "vuln", "high", "XML 외부 엔티티(XXE)",
             "외부 엔티티를 켜면 파일 유출·SSRF 로 이어질 수 있어요.",
             pattern=re.compile(r"(etree\.parse\s*\(|lxml.*XMLParser\s*\((?![^)]*resolve_entities\s*=\s*False)|DocumentBuilderFactory)"),
             fix="외부 엔티티를 끄거나 defusedxml 을 쓰세요.",
             suggestion="from defusedxml import ElementTree"),
    Scenario("VULN-COOKIE-16", "vuln", "medium", "안전하지 않은 쿠키",
             "httponly·secure 없이 쿠키를 쓰면 탈취·전송 위험이 있어요.",
             pattern=re.compile(r"set_cookie\s*\((?![^)]*httponly\s*=\s*True)[^)]*\)", I),
             fix="httponly=True, secure=True 를 설정하세요.",
             suggestion="resp.set_cookie(k, v, httponly=True, secure=True, samesite='Lax')"),
    Scenario("VULN-REDIRECT-17", "vuln", "medium", "오픈 리다이렉트",
             "사용자 입력으로 리다이렉트하면 피싱에 악용돼요.",
             pattern=re.compile(r"redirect\s*\(\s*request\.(args|values|GET|params|query)"),
             fix="허용 목록 안의 URL 로만 리다이렉트하세요.",
             suggestion="허용된 경로(화이트리스트)만 사용"),

    # ── 에이전트 과잉권한(agency) ────────────────────────
    Scenario("AGY-RMRF-01", "agency", "critical", "파괴적 파일 삭제",
             "시스템·홈·전체를 지우는 명령이에요. 되돌릴 수 없어요.",
             pattern=re.compile(r"rm\s+-[rf]{1,2}\s+(/|~|\*|/\*|\$HOME)"),
             fix="대상 경로를 좁히고 사람이 확인하게 하세요.",
             suggestion="rm -i ./build   # 확인 후, 좁은 범위"),
    Scenario("AGY-DROP-02", "agency", "critical", "DB 파괴 쿼리",
             "테이블·DB 를 통째로 지우는 명령이에요.",
             pattern=re.compile(r"\b(DROP\s+(TABLE|DATABASE)|TRUNCATE\s+TABLE|DELETE\s+FROM\s+\w+\s*;)", I),
             fix="운영 DB 에는 직접 실행하지 말고 마이그레이션·백업 후 진행하세요.",
             suggestion="-- 백업 후, 스테이징에서 먼저"),
    Scenario("AGY-PROD-03", "agency", "high", "운영 환경 직접 조작",
             "production/운영 리소스를 직접 건드리는 넓은 권한이에요.",
             pattern=re.compile(r"(production|운영\s*(디비|서버|배포)|prod[-_ ](db|database|server))", I),
             fix="읽기 전용·스테이징으로 범위를 좁히세요.",
             suggestion="환경을 staging 으로 지정하고 승인 절차를 두세요."),
    Scenario("AGY-CHMOD-04", "agency", "high", "chmod 777",
             "모두에게 읽기·쓰기·실행 권한을 주면 위험해요.",
             pattern=re.compile(r"chmod\s+(-R\s+)?777\b"),
             fix="필요한 최소 권한만 주세요(예: 644/750).",
             suggestion="chmod 750 script.sh"),
    Scenario("AGY-FORCE-05", "agency", "medium", "강제/검증 우회 플래그",
             "--force·--no-verify 는 안전장치를 건너뛰어요.",
             pattern=re.compile(r"(--force\b|--no-verify\b|git\s+push\s+.*--force)"),
             fix="정말 필요한지 확인하고 사유를 남기세요.",
             suggestion="가능하면 플래그 없이 진행하세요."),
    Scenario("AGY-PIPE-06", "agency", "high", "원격 스크립트 즉시 실행",
             "받은 스크립트를 바로 실행하면 내용 검증 없이 코드가 돌아요.",
             pattern=re.compile(r"(curl|wget)\s+[^\n|]*\|\s*(sudo\s+)?(sh|bash)"),
             fix="내려받아 내용을 확인한 뒤 실행하세요.",
             suggestion="curl -o s.sh URL && less s.sh && bash s.sh"),
]
